package prog;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;
import java.util.List;
import prog.methods.Fonction;
import prog.results.Resultat;

import java.util.List;

import prog.methods.Fonction;
import prog.results.Resultat;

//#############################################
//## file: Parser.java
//## Generated by Byacc/j
//#############################################
/**
 * BYACC/J Semantic Value for parser: Parser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class ParserVal
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval;

/**
 * object value of this 'union'
 */
public Object obj;

public Resultat rval;

public List<Resultat> lval;

public boolean bval;

public Fonction fval;

//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public ParserVal()
{
}
/**
 * Initialize me as an int
 */
public ParserVal(int val)
{
  ival=val;
}

/**
 * Initialize me as a double
 */
public ParserVal(double val)
{
  dval=val;
}

/**
 * Initialize me as a string
 */
public ParserVal(String val)
{
  sval=val;
}

/**
 * Initialize me as an Object
 */
public ParserVal(Object val)
{
  obj=val;
}

public ParserVal(boolean val)
{
  bval=val;
}

public ParserVal(Resultat val)
{
  rval=val;
}

public ParserVal(List<Resultat> val)
{
  lval=val;
}

public ParserVal(Fonction val)
{
  fval=val;
}
}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
